### ISSUE TITLE
installing daisyui

### ISSUE THREAD

**Issue by Neoplatonist** [Neoplatonist/bog-republic-ts#7]
Please install daisyUI and check that it works on the Home Page (`/pages/index.tsx`)

https://daisyui.com/docs/install/

Don't forget to appropriately name the git branch `feat/daisyui` and make the PR to our project's branch `ui`.

Your git commit message should look like `git commit -m "feat: closes gh-7 added daisyUI"`. This will automatically close this issue

**Comment by TofuSupreme** [comment]
Currently working on this, but have an error. 
Screen shot is below:
![image](https://user-images.githubusercontent.com/67456282/195534738-6d9a5065-0542-4d16-a936-cdb62cfda673.png)

**Comment by Neoplatonist** [comment]
Hmm, for the eslint error that occurred. I fixed it using this comment above plugins. `// eslint-disable-next-line global-require`

It should look something like this:
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  // eslint-disable-next-line global-require
  plugins: [require("daisyui")],
};
```

I hope this helps!
